name: Github Actions
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5
    - uses: jiro4989/setup-nim-action@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - run: nimble install -y libcurl
    - run: nimble install -y zippy
    - run: nimble install -y webby
    - run: nim c tests/debug_server.nim

    - run: nimble test -y --gc:refc
    - run: nimble test -y --gc:arc
    - run: nimble test -y --gc:orc
    - run: nimble test -d:release -y --gc:orc

    - run: nimble test -y --gc:arc --threads:on
